
import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Mail } from 'lucide-react';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/home/Footer';

const CertifiedRealBroker: React.FC = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      
      <main className="flex-grow">
        {/* Hero Section */}
        <section className="relative py-20 bg-gradient-to-br from-gray-50 to-gray-100">
          <div className="container mx-auto px-4 md:px-6">
            <div className="flex flex-col lg:flex-row items-center gap-12">
              <div className="flex-1 space-y-6">
                <h1 className="text-4xl md:text-5xl font-bold text-gray-900 tracking-tight">
                  Certified RealBroker™
                </h1>
                <p className="text-xl md:text-2xl font-medium text-gray-700">
                  Become a Certified RealBroker™ Partner
                </p>
                <p className="text-lg text-gray-600 max-w-2xl">
                  Join the elite ranks of Certified RealBrokers™ and take your real estate career to the next level.
                </p>
                <Button 
                  size="lg" 
                  className="bg-realtor-600 hover:bg-realtor-700 text-white px-6 py-3 rounded-lg font-medium"
                >
                  Get Started <Mail className="ml-2 h-5 w-5" />
                </Button>
              </div>
              <div className="flex-1">
                <img 
                  src="https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80" 
                  alt="Professional using laptop" 
                  className="rounded-lg shadow-xl w-full object-cover"
                />
              </div>
            </div>
          </div>
        </section>
        
        {/* Main Content */}
        <section className="py-16">
          <div className="container mx-auto px-4 md:px-6">
            <div className="max-w-3xl mx-auto prose lg:prose-xl">
              <p>
                Through our certification and onboarding program, agents gain access to high-quality leads generated by RealBroker Concierge, connecting you with motivated buyers and sellers actively seeking a seamless real estate experience.
              </p>
              
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mt-8">Technology-Driven Success</h2>
              <p>
                Leverage cutting-edge tools through the RealBroker Platform, including a robust CRM, advanced transaction management systems, and buyer/seller lead generation. Our tech-first approach empowers you to close more deals, operate remotely, and work efficiently, without the constraints of traditional brick-and-mortar brokerages.
              </p>
              
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mt-8">Agent-Focused Freedom</h2>
              <p>
                At RealBroker, we prioritize your success. Enjoy higher commission splits, unparalleled freedom, and fewer restrictions compared to conventional firms. Your success drives our mission, which is why we also offer stock options and incentives to reward your achievements.
              </p>
              
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mt-8">Flexible Virtual Environment</h2>
              <p>
                Embrace the flexibility of a cloud-based infrastructure. Collaborate seamlessly with clients and peers online, reduce overhead costs, and unlock the freedom to work from anywhere.
              </p>
              
              <p className="font-medium mt-8">
                As a Certified RealBroker™, you'll have the tools, network, and support to thrive in a modern real estate ecosystem while maximizing your earning potential. Partner with us to redefine your real estate journey.
              </p>
              
              <p className="mt-8">
                "Certified RealBroker" is following the trend of tech-focused real estate platforms globally, which are changing how real estate transactions are done by leveraging technology to create efficiencies for both agents and consumers.
              </p>
            </div>
          </div>
        </section>
        
        {/* CTA Section */}
        <section className="py-16 bg-gray-50">
          <div className="container mx-auto px-4 md:px-6">
            <Card className="max-w-4xl mx-auto overflow-hidden">
              <div className="flex flex-col md:flex-row">
                <div className="md:w-2/5 bg-realtor-600 p-8 text-white flex flex-col justify-center">
                  <h3 className="text-2xl md:text-3xl font-bold mb-4">
                    Ready to Transform Your Real Estate Career?
                  </h3>
                  <p className="text-white/80">
                    Become a Certified RealBroker™ and access exclusive tools, resources, and support.
                  </p>
                </div>
                <CardContent className="md:w-3/5 p-8 bg-white">
                  <h4 className="text-xl font-semibold mb-4">
                    Are you interested in becoming a Certified RealBroker™?
                  </h4>
                  <p className="text-gray-600 mb-6">
                    Want to learn more about how you can become a Certified RealBroker™ and expedite your Real Estate agency? Get in touch with us.
                  </p>
                  <div className="flex items-center gap-4 flex-wrap">
                    <a 
                      href="mailto:join@realbroker.app" 
                      className="inline-flex items-center justify-center gap-2 bg-realtor-600 hover:bg-realtor-700 text-white px-5 py-3 rounded-lg font-medium transition-colors"
                    >
                      <Mail className="h-5 w-5" />
                      join@realbroker.app
                    </a>
                    <Button variant="outline" className="border-realtor-600 text-realtor-600 hover:bg-realtor-50">
                      Schedule a Call
                    </Button>
                  </div>
                </CardContent>
              </div>
            </Card>
          </div>
        </section>
      </main>
      
      <Footer />
    </div>
  );
};

export default CertifiedRealBroker;
