// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayxhtlzyhpsjykxxnqqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5eGh0bHp5aHBzanlreHhucXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTEwMzksImV4cCI6MjA1Nzk2NzAzOX0.HB-PnThw1SJQXWzFZSeDFI2zO-GKhPTufGr3RtB4uRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);